// Mock data for the salon app
// In production, this would come from a backend API

export const SALON_DATA = {
  id: '1',
  name: 'TASARIMHANE',
  type: 'Bay/Bayan Güzellik Salonu',
  owner: 'Mesut AKÇAKOCA',
  foundedYear: '2014',
  staffCount: '4 Kişi',
  phone: '+90 555 123 4567',
  whatsapp: '+90 555 123 4567',
  address: 'Atatürk Caddesi No: 25, Merkez/Düzce',
  about: 'TASARIMHANE olarak 2014 yılından bu yana müşterilerimize en kaliteli hizmeti sunmak için çalışıyoruz. Müşteri memnuniyetini ön planda tutarak, sektördeki yenilikleri ve değişikliklere kusursuz bir şekilde uyum sağlayarak, bu yolda emin adımlarla ilerlemeye devam ediyoruz. Başarıya profesyonel bir ekiple ulaşmanın önemini biliyor ve her gün daha iyisini hedefliyoruz.',
  workingHours: [
    { day: 'Pazartesi', hours: '10:00 - 22:00', isOpen: true },
    { day: 'Salı', hours: '10:00 - 22:00', isOpen: true },
    { day: 'Çarşamba', hours: '10:00 - 22:00', isOpen: true },
    { day: 'Perşembe', hours: '10:00 - 22:00', isOpen: true },
    { day: 'Cuma', hours: '10:00 - 22:00', isOpen: true },
    { day: 'Cumartesi', hours: '10:00 - 22:00', isOpen: true },
    { day: 'Pazar', hours: '10:00 - 22:00', isOpen: true },
  ],
  socialMedia: {
    facebook: 'https://facebook.com/tasarimhane',
    instagram: 'https://instagram.com/tasarimhane',
    twitter: 'https://twitter.com/tasarimhane',
    tiktok: 'https://tiktok.com/@tasarimhane',
  },
  images: [
    'https://picsum.photos/seed/salon1/800/400',
    'https://picsum.photos/seed/salon2/800/400',
    'https://picsum.photos/seed/salon3/800/400',
    'https://picsum.photos/seed/salon4/800/400',
    'https://picsum.photos/seed/salon5/800/400',
    'https://picsum.photos/seed/salon6/800/400',
  ],
};

export const PERSONNEL_DATA = [
  {
    id: '1',
    name: 'Fatma Gül',
    surname: 'Özkaya',
    role: 'Kadın/Erkek Kuaförü',
    image: 'https://picsum.photos/seed/fatma/200/200',
    services: [
      'Saç Bakımı',
      'Saç Yıkama+Fön',
      'Saç Düzleştirme',
      'Saç Boyama',
      'Ağda(Tüm Vücut)',
      'Cilt Bakımı',
    ],
    about: 'Merhaba,\nBen Fatma Gül . TASARIMHANE salonunda yukarıda listelenen hizmetleri veriyorum. Çarşamba günleri hariç haftanın 6 günü 12:00-21:00 saatleri arasında seni de salonumuza bekliyoruz.',
    workingHours: '12:00 - 21:00',
    dayOff: 'Çarşamba',
  },
  {
    id: '2',
    name: 'İbrahim',
    surname: 'AKÇAKOCA',
    role: 'Kadın/Erkek Kuaförü',
    image: 'https://picsum.photos/seed/ibrahim/200/200',
    services: [
      'Saç Kesimi',
      'Sakal Tıraşı',
      'Saç Boyama',
      'Saç Şekillendirme',
    ],
    about: 'Merhaba,\nBen İbrahim. TASARIMHANE salonunda yukarıda listelenen hizmetleri veriyorum.',
    workingHours: '10:00 - 22:00',
    dayOff: 'Pazartesi',
  },
  {
    id: '3',
    name: 'İsmet',
    surname: 'Yiğit',
    role: 'Kadın/Erkek Kuaförü',
    image: 'https://picsum.photos/seed/ismet/200/200',
    services: [
      'Saç Kesimi',
      'Saç Boyama',
      'Saç Bakımı',
    ],
    about: 'Merhaba,\nBen İsmet. TASARIMHANE salonunda yukarıda listelenen hizmetleri veriyorum.',
    workingHours: '10:00 - 22:00',
    dayOff: 'Salı',
  },
  {
    id: '4',
    name: 'Mesut',
    surname: 'AKÇAKOCA',
    role: 'Kadın/Erkek Kuaförü',
    image: 'https://picsum.photos/seed/mesut/200/200',
    services: [
      'Saç Kesimi',
      'Sakal Tıraşı',
      'Saç Şekillendirme',
      'Saç Boyama',
    ],
    about: 'Merhaba,\nBen Mesut. TASARIMHANE salonunun sahibi ve kuaförüyüm.',
    workingHours: '10:00 - 22:00',
    dayOff: 'Pazar',
  },
  {
    id: '5',
    name: 'Osman Baki',
    surname: 'Akçakoca',
    role: 'Kadın/Erkek Kuaförü',
    image: 'https://picsum.photos/seed/osman/200/200',
    services: [
      'Saç Kesimi',
      'Saç Boyama',
    ],
    about: 'Merhaba,\nBen Osman Baki. TASARIMHANE salonunda hizmet veriyorum.',
    workingHours: '10:00 - 22:00',
    dayOff: 'Çarşamba',
  },
  {
    id: '6',
    name: 'Şevket',
    surname: 'Demirkaya',
    role: 'Kadın/Erkek Kuaförü',
    image: null,
    services: [
      'Saç Kesimi',
      'Sakal Tıraşı',
    ],
    about: 'Merhaba,\nBen Şevket. TASARIMHANE salonunda hizmet veriyorum.',
    workingHours: '10:00 - 22:00',
    dayOff: 'Perşembe',
  },
  {
    id: '7',
    name: 'TASARIMHANE',
    surname: '.',
    role: 'Kadın/Erkek Kuaförü',
    image: 'https://picsum.photos/seed/tasarimhane/200/200',
    services: [
      'Tüm Hizmetler',
    ],
    about: 'TASARIMHANE salon hesabı.',
    workingHours: '10:00 - 22:00',
    dayOff: 'Yok',
  },
];
